redirects:
  alert-modes/out-of-office-mode: alerts/personal-alerts-management/out-of-office.md
  alerts/vacation-mode: alerts/personal-alerts-management/out-of-office.md
  administration/enforce-login: administration/sign-in-rules.md
  integrations-guideline/integrate-spike-with-sentry-webhook: integrations-guideline/integrate-spike-with-sentry.md
  oncall-schedules/export-on-call-schedule: oncall-schedules/calendar-sync-for-oncall/README.md
  integrations-guideline/integrate-spike-with-newrelic: integrations-guideline/integrate-spike-with-new-relic.md
  integrations-guideline/integrate-spike-with-ohdear: integrations-guideline/integrate-spike-with-oh-dear.md